### ISSUE TITLE
Number of detected events vs. epicentral distance

### ISSUE THREAD

**Issue by Cthuulhaa** [yetinam/pyocto#10]
Hi, 

I have been testing PyOcto to associate predicted P- and S-picks to events of which I already know the event time (it is not a continuous monitoring).

A while ago you [explained me](https://github.com/seisbench/seisbench/issues/261) how traces are chunked in windows for individual predictions and for this reason, the chosen start time when retrieving the waveforms affects the predicted picks. I assume that this will also affect the phase association and if enough false positives are introduced or if more real picks are missing, more picks will be associated to false events.

In this example, I retrieve waveform data starting 2 seconds before the event time and for stations within an epicentral distance of 70 km. Here the picks were associated to 2 events:

![PhAssoc_event1-1](https://github.com/yetinam/pyocto/assets/81183635/2113c1c9-e0ab-41d6-906a-4f13ac82b551)
![PhAssoc_event2-1](https://github.com/yetinam/pyocto/assets/81183635/20a70cc0-5e8d-4086-9949-81ee67a513ad)

This is the case for a start time 4 seconds before the event time (max. epicentral distance 70 km):

![PhAssoc_event1-1](https://github.com/yetinam/pyocto/assets/81183635/38777085-e3c7-4834-8005-fa99e35b183e)

As I increase the epicentral distance (more picks), the picks are associated to even more events. What I notice, however is that no optimal set of picks is associated to any of those events:

Start time 2 seconds before, epicentral distance 100 km:

![PhAssoc_event1-1](https://github.com/yetinam/pyocto/assets/81183635/6b611b97-962a-4165-83ab-990bdc5e7249)
![PhAssoc_event2-1](https://github.com/yetinam/pyocto/assets/81183635/6fb1820a-7fd6-4593-af6b-623511c6fdf0)

Start time 2 seconds before event, epicentral distance 130 km:

![PhAssoc_event1-1](https://github.com/yetinam/pyocto/assets/81183635/28510fa1-88bb-4c87-8590-debbf57682fb)
![PhAssoc_event2-1](https://github.com/yetinam/pyocto/assets/81183635/18b8cc14-9d3d-46b7-a0b8-475e476bed52)
![PhAssoc_event3-1](https://github.com/yetinam/pyocto/assets/81183635/f0e47f2b-47d6-4539-bc7c-4d875e77ac3c)
![PhAssoc_event4-1](https://github.com/yetinam/pyocto/assets/81183635/d1234210-17b1-4b64-a881-640c826735d8)
![PhAssoc_event5-1](https://github.com/yetinam/pyocto/assets/81183635/07797c54-713d-4208-a198-479a83953803)
![PhAssoc_event6-1](https://github.com/yetinam/pyocto/assets/81183635/409222d4-da3a-4318-9e72-3f53ddfda303)

Do you have any suggestions to optimally select such parameters?

Cheers!

**Comment by Cthuulhaa** [comment]
Hi @yetinam,

here an update for the sake of completeness: I tested changing both, the tolerance parameters and the minimum number of picks per event and it solved the issue, as you suspected. I did not modify the velocity model. I use Crust1.0, which has appropriate velocities for the continental upper crust.

For the event I showed in my first post, with start time 2 seconds before the event time and with picks on stations with maximal epicentral distance of 100 km, PyOcto correctly associates the picks to one event:

![PhAssoc_event1_2 png-1](https://github.com/yetinam/pyocto/assets/81183635/4c1689c8-6875-4862-9b77-77c2a13ca201)

Here are 2 local earthquakes with their associated phases for stations within 90 km:

![eq_4s_90km png-1](https://github.com/yetinam/pyocto/assets/81183635/09855dc9-9d88-434f-854b-062714d3b494)
![eq_6s_90km png-1](https://github.com/yetinam/pyocto/assets/81183635/042a6599-f657-491e-a01a-b9d8b8dda9b5)

What I have noticed is that if there are too many stations with picks (some 25 stations), the phase association takes way longer and for some time windows does not associate any phases to the event. In this example many phases are lost:

![desastre_24stations png-1](https://github.com/yetinam/pyocto/assets/81183635/75aaf267-2b4b-4458-b1a3-539d225c297f)

I suspect that in cases where there are over ~21 stations with picks I can use the picks on the ~20 closest stations and it should solve that issue.

**Comment by yetinam** [comment]
Thanks for the detailed analysis of your results. The non-associated picks are likely related to a bad location estimate of PyOcto which will in turn lead to not matching all picks. Seems like there's some room for improvement in the location estimation strategy.
