### ISSUE TITLE
Question: Velocity model requirements relative to station coverage

### ISSUE THREAD

**Issue by 10go-L** [yetinam/pyocto#13]
Hi!

I'm currently using PyOcto and have a question regarding the requirements for the velocity model.
Is it a requirement for the velocity model to include the geographical locations of all seismic stations used in the event location process?

I have run it in both ways and just wondering if you have any insight.

Cheers,
D

**Comment by yetinam** [comment]
Hi! I'm not totally sure I understand the question. PyOcto velocity models are 1D or homogeneous and not associated with a specific region. In case you're asking about the search region, the stations can be outside that region. Does that answer your question?
