### ISSUE TITLE
How to intepret the plausible artefact, i.e., a rectangle cluster?

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [yetinam/pyocto#15]
[Mariana_seismicity.pdf](https://github.com/user-attachments/files/16107477/Mariana_seismicity.pdf)
Hi.
This is the result of pyocto applied to Marianan trench. The triangles denote an OBS array and the only land-based station, IU.GUMO. Notice a rectangular cluster of earthquakes, is this an artefact? Can you provide any explanation?
Any reply is much appreciated.

**Comment by yetinam** [comment]
Hi @JUNZHU-SEIS ,
yes, this is most likely an artifact. PyOcto uses a location search algorithm that optimizes for speed as it is called very often during the association process. On the downside, this leads to suboptimal locations. The best way to handle these artifacts is to relocate events with a proper location tool, for example, NonLinLoc. The `to_nonlinloc` function can help you to export your associated picks in an appropriate format.
