### ISSUE TITLE
Too many file descriptors open using VelocityModel1D and OctoAssociator.from_area()

### ISSUE THREAD

**Issue by marcopovitch** [yetinam/pyocto#2]
Hi thanks for providing us  this useful software. 
It seems calling `pyocto.OctoAssociator.from_area()` within a loop with a `VelocityModel1D` model (created outside the loop) leads to a lot of open files to the one created by `VelocityModel1D.create_model()` (it can be verified usinf `lsof`). It quickly exhausts the limit number of file descriptors, as a work around ulimit -n unlimited do the job ...

I do not observed this behavior using replacing `VelocityModel1D` with a `VelocityModel0D`. I am using OSX.

Regards
Marc

**Comment by yetinam** [comment]
Hi Marc,
thanks for reporting this. I had a look and there's indeed a missing `fclose` statement in [this function](https://github.com/yetinam/pyocto/blob/6d3b25232e775a2d7e51bcc60fec58518c20fee5/src/VelocityModel.cpp#L115). I'll fix it later today.

**Comment by yetinam** [comment]
The bug should be fixed now. The CI is currently building the wheels and pushing it to PyPI as v0.1.1. Once is pushed, could you give it a quick try if the issue is fixed?

**Comment by marcopovitch** [comment]
thanks a lot, the issue is fixed ! 👍
