### ISSUE TITLE
 event time after pick time

### ISSUE THREAD

**Issue by wennanwu** [yetinam/pyocto#22]
I observed that the P-wave and S-wave pick times I obtained appear to be earlier than the actual origin times for certain events. For example:

Here is a calculated event time:

idx	time	x	y	z	picks	latitude	longitude	depth
564	2024-04-12 18:44:37.160830+00:00	-11.0614	7.6339	13.6719	73	23.3689	120.1918	13.6719
This timestamp corresponds to a recorded earthquake in the catalog.

However, upon further examination of the relevant pick data, I encountered the following:

event_idx	pick_idx	residual	station	phase	time	timestamp
564	1462	-0.1663	TW.C004	P	1712947482.45	1712947482.45
In this case, the P-wave pick time appears as:

P-wave pick time: 2024-04-12 18:29:40.55 (Station: TW.C004)
Event origin time: 2024-04-12 18:44:37.16
The pick time is earlier than the event origin time, which I find puzzling.

**Comment by yetinam** [comment]
Sorry for the late reply. Yes, that's exactly how the `pick_idx` is defined.
