### ISSUE TITLE
Question: what is the difference between the “tolerance” parameter for velocity models and the “pick_match_tolerance” parameter for the OctoAssociator class?

### ISSUE THREAD

**Issue by zhong-yy** [yetinam/pyocto#8]
Based on the descriptions in the [document](https://pyocto.readthedocs.io/en/latest/pages/associator.html#:~:text=pick_match_tolerance%20(float)%20%E2%80%93%20Maximum%20difference%20between%20the%20predicted%20travel%20time%20and%20the%20observed%20time%20for%20associating%20a%20pick%20to%20an%20origin%20in%20the%20refinement%20step.) and the [example](https://colab.research.google.com/github/yetinam/pyocto/blob/main/examples/02_velocity_models.ipynb), it seems that both `tolerance` and `pick_match_tolerance` refer to the maximum allowed difference between the observed and predicted arrival time. Are they the same?

Thank you for providing this amazing package!

**Comment by yetinam** [comment]
Hi @zhong-yy,
indeed, this is a little confusing, but the parameters are different. The 'tolerance' of the velocity model is the allowed deviation from the predicted travel time when checking if a pick could originate from a volume. The `pick_match_tolerance` is for the step of matching picks to the origin, i.e., when PyOcto checks which picks are consistent with an origin. In most cases, you'll want to use the same parameters for both values, but it sometime might make sense to choose different tolerances for the search and for the matching step.
